name: multi_l2d
channels:
  - defaults
  - pytorch

dependencies:
  - pip=20.1.1
  - python=3.7
  - numpy-base=1.18.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - scipy=1.4.1
  - pytorch=1.11.0
  - torchvision=0.5.0
  - pandas=1.2.0
  - seaborn=0.10.1
  - tqdm=4.47.0
  - pip:
    - jupyter==1.0.0
    - jupyterlab==2.1.51
    - nbformat==5.0.7
    - notebook==6.0.3
    - numpy==1.19.0
    - scikit-learn==0.23.1
    - torchvision==0.6.1
    - tueplots