name: multi_l2d
channels:
  - defaults
  - pytorch

dependencies:
  - pip
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - pytorch
  - torchvision
  - pandas
  - seaborn
  - tqdm
  - pip:
    - jupyter
    - jupyterlab
    - notebook
    - numpy
    - scikit-learn
    - torchvision
    - tueplots